name: Dependency SUbmission

on:
  workflow_dispatch:
  push:

permissions: 
  id-token: write
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dotnet Info Before
        run: dotnet --info
      - name: Build
        run: dotnet build
      - name: Component detection 
        if: runner.os != 'Windows'
        uses: jhutchings1/component-detection-action@v0.0.1
